CREATE COLUMN TABLE "SCH_COMP"."sap.hana.im.ess.eg.deploy.hier::ATTRIBUTE_GRAPH_NODES" ("HIERARCHY_ID" INTEGER NOT NULL ,
	 "NAME" NVARCHAR(200) NOT NULL ,
	 "LEVEL_NUM" INTEGER CS_INT,
	 "IS_OPTION" INTEGER CS_INT) UNLOAD PRIORITY 5 AUTO MERGE
;


CREATE COLUMN TABLE "SCH_COMP"."sap.hana.im.ess.eg.deploy.hier::ATTRIBUTE_GRAPH_EDGES" ("HIERARCHY_ID" INTEGER  NOT NULL ,
	 "ATT_NAME" NVARCHAR(200),
	 "PARENT_ATT_NAME" NVARCHAR(200),
	 "LABEL" NVARCHAR(10)) UNLOAD PRIORITY 5 AUTO MERGE 
;

CREATE COLUMN TABLE "SCH_COMP"."sap.hana.im.ess.eg.deploy.hier::HIERARCHY_TO_CRAWL" ("HIERARCHY_ID" INTEGER NOT NULL ,
	 "RESULT_NODE" NVARCHAR(5000),
	 "PRED_NODE" NVARCHAR(5000),
	 "LEVEL_NAME" NVARCHAR(200),
	 "IS_LEAF" INTEGER CS_INT,
	 "LEVEL_NUM" INTEGER CS_INT) UNLOAD PRIORITY 5 AUTO MERGE 
;